# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-metaflow-blog',
                'doc_host': 'https://Hrsh-12.github.io',
                'git_url': 'https://github.com/Hrsh-12/nbdev-metaflow-blog',
                'lib_path': 'nbdev_metaflow_blog'},
  'syms': {'nbdev_metaflow_blog.core': {'nbdev_metaflow_blog.core.foo': ('core.html#foo', 'nbdev_metaflow_blog/core.py')}}}
